### ISSUE TITLE
运行后，有redis的错误？

### ISSUE THREAD

**Issue by juventusryp** [hopeaktian/daoink#1]
你好，我按照配置运行后，出现如下错误：

```
flask.cli.NoAppException
NoAppException: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "H:\python_vbox\daoink-master-AfXXfSTJ\lib\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "H:\daoink-master\app\__init__.py", line 7, in <module>
    from controllers.printer import printer
  File "H:\daoink-master\app\controllers\printer.py", line 9, in <module>
    from app.config import RedisConfig
ImportError: cannot import name RedisConfig
```
但是在config中并未看到相关的配置，求解具体原因？

**Comment by hopeaktian** [comment]
这个是我忘记写了 [尴尬] ，前段时间有些忙没维护，最近重新整理维护一下。 @juventusryp
