### ISSUE TITLE
安装的时候报错

### ISSUE THREAD

**Issue by qxbug** [hopeaktian/daoink#3]
到这个步骤的时候报错
```
python __init__.py
Traceback (most recent call last):
  File "__init__.py", line 7, in <module>
    from controllers.printer import printer
  File "/www/wwwroot/app/controllers/printer.py", line 5, in <module>
    from app.models import db, User, Order
ImportError: No module named app.models
```
另外木有数据库怎么办啊 需要自己建表么

**Comment by hopeaktian** [comment]
![image](https://user-images.githubusercontent.com/29337299/68653545-ee3d0180-0566-11ea-86b4-4584222a236a.png)
先配置数据库信息，可在本地创建一个数据库用于测试。

**Comment by hopeaktian** [comment]
> 到这个步骤的时候报错
> 
> ```
> python __init__.py
> Traceback (most recent call last):
>   File "__init__.py", line 7, in <module>
>     from controllers.printer import printer
>   File "/www/wwwroot/app/controllers/printer.py", line 5, in <module>
>     from app.models import db, User, Order
> ImportError: No module named app.models
> ```
> 
> 另外木有数据库怎么办啊 需要自己建表么

需要自己建库，表结构会在第一次运行程序后自动创建。

**Comment by yunlancn** [comment]
我也遇到这个问题了，确定连接信息是正确的，貌似后端是正常的，前端就不行，提示一样的错误
